name: Send tweet message to telegram workflow

on:
  schedule:
    - cron: "*/30 * * * *" # run every thirty minutes
  workflow_dispatch:  # manual trigger for debug purposes

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r twitter/requirements.txt

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          python twitter/main.py EuropeElects Portugal # Portuguese polls
          python twitter/main.py mariana_maz94 "BILHETES:" # Benfica tickets
          
      - name: Add changes to last.txt
        run: |
          git add -A twitter/

      - name: Commit all changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Update latest date sent
          branch: ${{ github.head_ref }}

